not_read_in_file = ['avg_c2_oil_temperature_6h', 'avg_c2_oil_temperature_12H',
                    'avg_c1_brass_suction_temperature_6h', 'avg_c1_brass_suction_temperature_12H',
                    'avg_c2_brass_suction_temperature_12H', 'avg_maximum_pressure_6h',
                    'avg_maximum_pressure_12H', 'avg_maximum_pressure_24H', 'avg_c1_brass_coupling_temperature_6h',
                    'avg_c1_brass_coupling_temperature_12H',
                    'avg_c2_brass_coupling_temperature_6h', 'avg_c2_brass_coupling_temperature_12H',
                    'avg_c1_c2_oil_temperature_difference_6h',
                    'avg_c1_c2_oil_temperature_difference_12H',
                    'avg_c1_oil_temperature_6h', 'avg_c1_oil_temperature_12H',
                    'avg_air_temperature_6h', 'avg_air_temperature_12H',
                    'avg_chamber_pressure_6h', 'avg_chamber_pressure_12H',
                    'avg_line_filling_time_6h', 'avg_line_filling_time_12H', 'avg_line_filling_time_24H',
                    'avg_current_start_ups_6h', 'avg_current_start_ups_12H', 'avg_current_start_ups_24H',
                    'avg_total_start_ups_6h', 'avg_total_start_ups_12H', 'avg_total_start_ups_24H',
                    'avg_maximum_inverter_system_speed_6h', 'avg_maximum_inverter_system_speed_12H',
                    'avg_maximum_inverter_system_speed_24H', 'avg_line_pressure_6h', 'avg_line_pressure_12H',
                    'avg_minimum_pressure_6h', 'avg_minimum_pressure_12H',
                    'avg_minimum_pressure_24H', 'avg_oil_low_temperature_start_up_exclusion_6h',
                    'avg_oil_low_temperature_start_up_exclusion_12H', 'avg_oil_low_temperature_start_up_exclusion_24H',
                    'avg_compressor_status_6h', 'avg_compressor_status_12H', 'avg_compressor_status_24H',
                    'avg_compressor_operation_mode_6h', 'avg_compressor_operation_mode_12H',
                    'avg_compressor_operation_mode_24H',
                    'min_high_part_enabling_hours_6h', 'min_high_part_enabling_hours_12H',
                    'min_low_part_enabling_hours_6h', 'min_low_part_enabling_hours_12H',
                    'min_high_part_running_hours_6h', 'min_high_part_running_hours_12H',
                    'min_low_part_running_hours_6h', 'min_low_part_running_hours_12H',
                    'min_high_part_load_hours_6h', 'min_high_part_load_hours_12H',
                    'min_low_part_load_hours_6h', 'min_low_part_load_hours_12H',
                    'avg_inverter_rpm_speed_6h', 'avg_inverter_rpm_speed_12H', 'avg_inverter_rpm_speed_24H',
                    'avg_idle_running_time_6h', 'avg_idle_running_time_12H', 'avg_idle_running_time_24H',
                    'min_high_part_oil_operating_hours_service_6h', 'min_high_part_oil_operating_hours_service_12H',
                    'min_low_part_oil_operating_hours_service_6h',
                    'min_low_part_oil_operating_hours_service_12H',
                    'min_high_part_oil_filter_operating_hours_service_6h',
                    'min_high_part_oil_filter_operating_hours_service_12H',
                    'min_low_part_oil_filter_operating_hours_service_6h',
                    'min_low_part_oil_filter_operating_hours_service_12H',
                    'min_high_part_separator_filter_operating_hours_service_6h',
                    'min_high_part_separator_filter_operating_hours_service_12H',
                    'min_low_part_separator_filter_operating_hours_service_6h',
                    'min_low_part_separator_filter_operating_hours_service_12H',
                    'min_high_part_oil_hours_threshold_service_6h', 'min_high_part_oil_hours_threshold_service_12H',
                    'min_low_part_oil_hours_threshold_service_6h',
                    'min_low_part_oil_hours_threshold_service_12H',
                    'min_high_part_oil_filter_hours_threshold_service_6h',
                    'min_high_part_oil_filter_hours_threshold_service_12H',
                    'min_low_part_oil_filter_hours_threshold_service_6h',
                    'min_low_part_oil_filter_hours_threshold_service_12H',
                    'min_high_part_separator_filter_hours_threshold_service_6h',
                    'min_high_part_separator_filter_hours_threshold_service_12H',
                    'min_low_part_separator_filter_hours_threshold_service_6h',
                    'min_low_part_separator_filter_hours_threshold_service_12H',
                    'avg_c1_c2_oil_temperature_difference_28D', 'min_c1_oil_temperature_28D',
                    'min_low_part_oil_filter_operating_hours_service_7D',
                    'min_line_pressure_28D', 'min_low_part_running_hours_7D', 'avg_c1_brass_suction_temperature_28D',
                    'avg_chamber_pressure_28D',
                    'min_low_part_oil_filter_operating_hours_service_7D',
                    'min_high_part_oil_filter_hours_threshold_service_7D',
                    'min_high_part_separator_filter_operating_hours_service_7D', 'min_low_part_load_hours_7D',
                    'avg_c1_brass_coupling_temperature_28D',
                    'min_low_part_oil_operating_hours_service_7D',
                    'min_high_part_running_hours_7D',
                    'min_low_part_oil_filter_hours_threshold_service_7D',
                    'min_high_part_oil_operating_hours_service_7D',
                    'min_high_part_separator_filter_hours_threshold_service_7D',
                    'min_low_part_separator_filter_operating_hours_service_7D',
                    'min_high_part_enabling_hours_7D', 'avg_line_pressure_28D',
                    'min_c1_c2_oil_temperature_difference_28D',
                    'avg_air_temperature_28D', 'avg_c1_oil_temperature_28D', 'MIN_air_temperature_28D',
                    'min_high_part_load_hours_7D',
                    'min_c1_brass_suction_temperature_28D', 'min_c2_brass_suction_temperature_28D',
                    'min_chamber_pressure_28D', 'min_low_part_enabling_hours_7D',
                    'min_high_part_oil_filter_operating_hours_service_7D',
                    'min_low_part_separator_filter_hours_threshold_service_7D']

drop_list_high_low = ['high_part_enabling_hours', 'low_part_enabling_hours', 'high_part_running_hours',
                      'low_part_running_hours',
                      'high_part_load_hours', 'low_part_load_hours', 'high_part_oil_operating_hours_service',
                      'low_part_oil_operating_hours_service', 'high_part_oil_filter_operating_hours_service',
                      'low_part_oil_filter_operating_hours_service',
                      'high_part_separator_filter_operating_hours_service',
                      'low_part_separator_filter_operating_hours_service', 'high_part_oil_hours_threshold_service',
                      'low_part_oil_hours_threshold_service', 'high_part_oil_filter_hours_threshold_service',
                      'low_part_oil_filter_hours_threshold_service',
                      'high_part_separator_filter_hours_threshold_service',
                      'low_part_separator_filter_hours_threshold_service', 'min_high_part_running_hours_10M',
                      'min_high_part_running_hours_1H', 'min_low_part_running_hours_10M',
                      'min_low_part_running_hours_1H',
                      'min_high_part_load_hours_10M', 'min_high_part_load_hours_1H', 'min_low_part_load_hours_10M',
                      'min_low_part_load_hours_1H', 'min_high_part_load_hours_10M', 'min_high_part_load_hours_1H',
                      'min_low_part_load_hours_10M', 'min_low_part_load_hours_1H',
                      'min_high_part_oil_operating_hours_service_10M',
                      'min_high_part_oil_operating_hours_service_1H', 'min_low_part_oil_operating_hours_service_10M',
                      'min_low_part_oil_operating_hours_service_1H',
                      'min_high_part_oil_filter_operating_hours_service_10M',
                      'min_high_part_oil_filter_operating_hours_service_1H',
                      'min_low_part_oil_filter_operating_hours_service_10M',
                      'min_low_part_oil_filter_operating_hours_service_1H',
                      'min_high_part_separator_filter_operating_hours_service_10M',
                      'min_high_part_separator_filter_operating_hours_service_1H',
                      'min_low_part_separator_filter_operating_hours_service_10M',
                      'min_low_part_separator_filter_operating_hours_service_1H',
                      'min_high_part_oil_hours_threshold_service_10M',
                      'min_high_part_oil_hours_threshold_service_1H', 'min_low_part_oil_hours_threshold_service_10M',
                      'min_low_part_oil_hours_threshold_service_1H',
                      'min_high_part_oil_filter_hours_threshold_service_10M',
                      'min_high_part_oil_filter_hours_threshold_service_1H',
                      'min_low_part_oil_filter_hours_threshold_service_10M',
                      'min_low_part_oil_filter_hours_threshold_service_1H',
                      'min_high_part_separator_filter_hours_threshold_service_10M',
                      'min_high_part_separator_filter_hours_threshold_service_1H',
                      'min_low_part_separator_filter_hours_threshold_service_10M',
                      'min_low_part_separator_filter_hours_threshold_service_1H',
                      'min_high_part_oil_hours_threshold_service_7D', 'min_low_part_oil_hours_threshold_service_7D']

non_model_drops = ['dd', 'ts', 'tsMinute', 'device_id', 'timeX', 'RN', 'ind_shutdown_mal', 'ind_shutdown_mal_24H_next',
                   'ind_shutdown_mal_3D_next', 'ind_shutdown_mal_7D_next']
